### ISSUE TITLE
ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by qhhuang** [tion126/RNLive#1]
react-native run-ios
ENOENT: no such file or directory, uv_chdir
不是很懂RN -..- 第一个吃瓜问题

**Comment by qhhuang** [comment]
react-native start
就好了-..-

**Comment by tion126** [comment]
这个项目不是用react-native init 创建的哦  目录结构可能不太一样   iOS的话 ，如果只想看看效果，把 run scrip 里的注释打开 可以在运行的时候启动packager ，不用手动了
